### ISSUE TITLE
redirect url not changing

### ISSUE THREAD

**Issue by pratiksinghchauhan** [openmhealth/shimmer#107]
Why is the redirect url always like http://localhost:8083/authorize/misfit/callback ?

 I have exprienced this in many cases, I am not hosting my shimmer application on localhost, but other server, I have also tried to change parameter OPENMHEALTH_SHIMMER_DATAPROVIDERREDIRECTBASEURL in resource-server.env , I am using commands docker compose up -d , docker compose up -d resourceserver to run the project if that is requred

**Comment by umarhussain15** [comment]
See my pull request https://github.com/openmhealth/shimmer/pull/108

the issue in the code is that resource-server.env file has name of the variable wrong. So it picks values from application.yaml file. For docker set the values in env file as done in my PR

**Comment by kkmok** [comment]
Change the environment to "OPENMHEALTH_SHIMMER_DATA_PROVIDER_REDIRECT_BASE_URL"
