### ISSUE TITLE
grunt build Loading "Gruntfile.js" tasks...ERROR >> TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by ascooper57** [openmhealth/shimmer#23]
Option 2. Building from source and running on your host system
...
$ cd shim-server-ui/
$ npm install
npm WARN package.json shim-server-ui@0.2.1 No description
npm WARN package.json shim-server-ui@0.2.1 No repository field.
npm WARN package.json shim-server-ui@0.2.1 No README data
npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead
npm WARN deprecated ngmin@0.4.1: use ng-annotate instead
npm WARN deprecated find-file@0.1.4: Use the globby package instead
 
> fsevents@0.3.6 install /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> grunt-autoprefixer@0.4.2 postinstall /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/grunt-autoprefixer
> 

> ws@0.4.32 install /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> phantomjs@1.9.17 install /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/g9/93n9wtsd3g7fjkh63dm2n57c0000gp/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [=================================-------] 83% 0.0s
Received 9187K total.
Extracting zip contents
Removing /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/g9/93n9wtsd3g7fjkh63dm2n57c0000gp/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1435610996537/phantomjs-1.9.8-macosx -> /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs

> gifsicle@0.1.7 postinstall /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/grunt-contrib-imagemin/node_modules/gifsicle
> node index.js

✔ pre-build test passed successfully!

> jpegtran-bin@0.2.8 postinstall /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin
> node index.js

✔ pre-build test passed successfully!

> optipng-bin@0.3.11 postinstall /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/grunt-contrib-imagemin/node_modules/optipng-bin
> node index.js

✔ pre-build test passed successfully!

> pngquant-bin@0.1.7 postinstall /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer/shim-server-ui/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin
> node index.js

✓ pre-build test passed successfully
grunt-rev@0.1.0 node_modules/grunt-rev

karma-jasmine@0.1.5 node_modules/karma-jasmine

grunt-text-replace@0.3.12 node_modules/grunt-text-replace

grunt-contrib-concat@0.3.0 node_modules/grunt-contrib-concat

grunt-contrib-copy@0.4.1 node_modules/grunt-contrib-copy

grunt-contrib-clean@0.5.0 node_modules/grunt-contrib-clean
└── rimraf@2.2.8

grunt-concurrent@0.5.0 node_modules/grunt-concurrent
├── async@0.2.10
└── pad-stdio@0.1.1 (lpad@0.2.1)

grunt-contrib-htmlmin@0.1.3 node_modules/grunt-contrib-htmlmin
├── html-minifier@0.5.6
└── grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)

grunt-newer@0.6.1 node_modules/grunt-newer
├── async@0.2.9
└── rimraf@2.2.4 (graceful-fs@2.0.3)

grunt-contrib-cssmin@0.7.0 node_modules/grunt-contrib-cssmin
├── grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)
└── clean-css@2.0.8 (commander@2.0.0)

grunt-connect-proxy@0.1.11 node_modules/grunt-connect-proxy
├── lodash@0.9.2
└── http-proxy@1.1.6 (eventemitter3@1.1.1)

jshint-stylish@0.1.5 node_modules/jshint-stylish
├── text-table@0.2.0
└── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

time-grunt@0.2.10 node_modules/time-grunt
├── date-time@0.1.1
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── text-table@0.2.0
└── hooker@0.2.3

grunt-karma@0.9.0 node_modules/grunt-karma
└── lodash@2.4.2

load-grunt-tasks@0.4.0 node_modules/load-grunt-tasks
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
└── multimatch@0.1.0 (minimatch@0.2.14, lodash@2.4.2)

grunt-usemin@2.0.2 node_modules/grunt-usemin
├── debug@0.7.4
└── lodash@1.0.2

grunt-contrib-jshint@0.7.2 node_modules/grunt-contrib-jshint
└── jshint@2.3.0 (console-browserify@0.1.6, minimatch@0.4.0, underscore@1.4.4, shelljs@0.1.4, cli@0.4.5)

grunt-contrib-uglify@0.2.7 node_modules/grunt-contrib-uglify
├── grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)
└── uglify-js@2.4.23 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)

grunt-ngmin@0.0.3 node_modules/grunt-ngmin
└── ngmin@0.4.1 (astral@0.1.0, clone@0.1.19, commander@1.1.1, astral-angular-annotate@0.0.2, escodegen@0.0.28, esprima@1.0.4)

grunt-contrib-connect@0.5.0 node_modules/grunt-contrib-connect
├── connect-livereload@0.2.0
├── open@0.0.4
└── connect@2.7.11 (fresh@0.1.0, cookie-signature@1.0.1, pause@0.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.0.5, send@0.1.1, debug@2.2.0, formidable@1.0.14)

grunt-bower-install@1.0.2 node_modules/grunt-bower-install
├── wiredep@1.2.2 (chalk@0.1.1, through2@0.4.2, glob@3.2.11, lodash@1.3.1)
└── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)

grunt-svgmin@0.2.1 node_modules/grunt-svgmin
├── filesize@2.0.4
├── chalk@0.3.0 (ansi-styles@0.2.0, has-color@0.1.7)
└── svgo@0.3.7 (colors@0.6.2, whet.extend@0.9.9, coa@0.3.9, sax@0.5.8, js-yaml@3.3.1)

grunt-contrib-watch@0.5.3 node_modules/grunt-contrib-watch
├── gaze@0.4.3 (globule@0.1.0)
└── tiny-lr@0.0.4 (debug@0.7.4, faye-websocket@0.4.4, qs@0.5.6, noptify@0.0.3)

grunt@0.4.5 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── nopt@1.0.10 (abbrev@1.0.7)
├── exit@0.1.2
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.4)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
└── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)

grunt-google-cdn@0.2.2 node_modules/grunt-google-cdn
├── google-cdn@0.1.4 (debug@0.7.4, semver@2.0.11)
└── bower@0.9.2 (abbrev@1.0.7, stable@0.1.5, archy@0.0.2, colors@0.6.2, semver@1.1.4, nopt@2.0.0, async@0.2.10, mkdirp@0.3.5, rimraf@2.0.3, tmp@0.0.26, promptly@0.1.0, read-package-json@0.1.13, rc@0.0.8, glob@3.1.21, fstream@0.1.31, tar@0.1.20, lodash@1.0.2, unzip@0.1.7, request@2.11.4, hogan.js@2.0.0, update-notifier@0.1.10)

grunt-autoprefixer@0.4.2 node_modules/grunt-autoprefixer
└── autoprefixer@0.8.20131213 (css-parse@1.6.0, css-stringify@1.4.1)

karma@0.12.37 node_modules/karma
├── di@0.0.1
├── graceful-fs@3.0.8
├── mime@1.3.4
├── colors@1.1.2
├── q@1.4.1
├── glob@5.0.12 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2)
├── rimraf@2.4.0 (glob@4.5.3)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── useragent@2.1.7 (lru-cache@2.2.4)
├── source-map@0.4.2 (amdefine@0.1.1)
├── http-proxy@0.10.4 (colors@0.6.2, pkginfo@0.3.0, utile@0.2.1)
├── connect@2.30.0 (cookie@0.1.3, bytes@2.1.0, utils-merge@1.0.0, cookie-signature@1.0.6, fresh@0.3.0, pause@0.0.1, response-time@2.3.1, vhost@3.0.0, content-type@1.0.1, on-headers@1.0.0, basic-auth-connect@1.0.0, parseurl@1.3.0, cookie-parser@1.3.5, depd@1.0.1, qs@2.4.2, method-override@2.3.3, debug@2.2.0, connect-timeout@1.6.2, serve-favicon@2.3.0, multiparty@3.3.2, http-errors@1.3.1, express-session@1.11.3, finalhandler@0.4.0, morgan@1.6.0, serve-static@1.10.0, type-is@1.6.3, serve-index@1.7.0, errorhandler@1.4.0, compression@1.5.0, csurf@1.8.3, body-parser@1.13.1)
├── lodash@3.9.3
├── log4js@0.6.26 (async@0.2.10, underscore@1.8.2, semver@4.3.6, readable-stream@1.0.33)
├── chokidar@1.0.3 (path-is-absolute@1.0.0, arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0, anymatch@1.3.0, fsevents@0.3.6)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)

karma-phantomjs-launcher@0.1.4 node_modules/karma-phantomjs-launcher
└── phantomjs@1.9.17 (which@1.0.9, progress@1.1.8, kew@0.4.0, request-progress@0.3.1, adm-zip@0.4.4, fs-extra@0.18.4, request@2.42.0, npmconf@2.1.1)

grunt-contrib-imagemin@0.3.0 node_modules/grunt-contrib-imagemin
├── filesize@1.10.0
├── chalk@0.2.1 (has-color@0.1.7, ansi-styles@0.2.0)
├── gifsicle@0.1.7 (log-symbols@1.0.2, bin-wrapper@0.3.4, bin-build@0.1.1)
├── jpegtran-bin@0.2.8 (log-symbols@1.0.2, bin-wrapper@0.3.4, bin-build@0.1.1)
├── optipng-bin@0.3.11 (log-symbols@1.0.2, bin-wrapper@0.3.4, bin-build@0.1.1)
└── pngquant-bin@0.1.7 (chalk@0.4.0, bin-wrapper@0.2.4)

$ cd ../shim-server-ui/
Alan-Cooper-MBP:shim-server-ui alan_cooper$ sudo npm install -g grunt-cli bower
Password:
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
grunt-cli@0.1.13 /usr/local/lib/node_modules/grunt-cli
├── nopt@1.0.10 (abbrev@1.0.7)
├── resolve@0.3.1
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

bower@1.4.1 /usr/local/lib/node_modules/bower
├── is-root@1.0.0
├── junk@1.0.2
├── stringify-object@1.0.1
├── user-home@1.1.1
├── chmodr@0.1.0
├── rimraf@2.4.0
├── abbrev@1.0.7
├── archy@1.0.0
├── opn@1.0.2
├── graceful-fs@3.0.8
├── lru-cache@2.6.4
├── bower-logger@0.2.2
├── bower-endpoint-parser@0.2.2
├── lockfile@1.0.1
├── nopt@3.0.3
├── retry@0.6.1
├── tmp@0.0.24
├── request-progress@0.3.1 (throttleit@0.0.2)
├── q@1.4.1
├── semver@2.3.2
├── fstream@1.0.7 (inherits@2.0.1)
├── p-throttler@0.1.1 (q@0.9.7)
├── promptly@0.2.0 (read@1.0.6)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── which@1.1.1 (is-absolute@0.1.7)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.8)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── insight@0.5.3 (object-assign@2.1.1, async@0.9.2, lodash.debounce@3.1.0, os-name@1.0.3, tough-cookie@0.12.1)
├── tar-fs@1.6.0 (pump@1.0.0, tar-stream@1.2.1)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, latest-version@1.0.1)
├── request@2.53.0 (caseless@0.9.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.6.0, isstream@0.1.2, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@2.3.3, form-data@0.2.0, combined-stream@0.0.7, bl@0.9.4, mime-types@2.0.14, http-signature@0.10.1, tough-cookie@2.0.0, hawk@2.3.1)
├── bower-registry-client@0.3.0 (graceful-fs@2.0.3, request-replay@0.2.0, rimraf@2.2.8, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
├── github@0.2.4 (mime@1.3.4)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── configstore@0.3.2 (object-assign@2.1.1, xdg-basedir@1.0.1, uuid@2.0.1, osenv@0.1.2, js-yaml@3.3.1)
├── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, through@2.3.7, readline2@0.1.1, chalk@0.5.1, lodash@2.4.2, cli-color@0.3.3, rx@2.5.3)
└── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)

$ bower install
? May bower anonymously report usage statistics to improve the tool over time? Yes
bower not-cached    git://github.com/moment/moment.git#~2.8.3
bower resolve       git://github.com/moment/moment.git#~2.8.3
bower not-cached    git://github.com/jquery/jquery.git#~1.11.0
bower resolve       git://github.com/jquery/jquery.git#~1.11.0
bower not-cached    git://github.com/angular/bower-angular.git#1.2.15
bower resolve       git://github.com/angular/bower-angular.git#1.2.15
bower not-cached    git://github.com/es-shims/es5-shim.git#~2.1.0
bower resolve       git://github.com/es-shims/es5-shim.git#~2.1.0
bower not-cached    git://github.com/angular/bower-angular-resource.git#1.2.15
bower resolve       git://github.com/angular/bower-angular-resource.git#1.2.15
bower not-cached    git://github.com/angular/bower-angular-cookies.git#1.2.15
bower resolve       git://github.com/angular/bower-angular-cookies.git#1.2.15
bower not-cached    git://github.com/angular/bower-angular-sanitize.git#1.2.15
bower resolve       git://github.com/angular/bower-angular-sanitize.git#1.2.15
bower not-cached    git://github.com/angular/bower-angular-scenario.git#1.2.15
bower resolve       git://github.com/angular/bower-angular-scenario.git#1.2.15
bower not-cached    git://github.com/angular-ui/ui-date.git#~0.0.4
bower resolve       git://github.com/angular-ui/ui-date.git#~0.0.4
bower not-cached    git://github.com/angular/bower-angular-route.git#1.2.15
bower resolve       git://github.com/angular/bower-angular-route.git#1.2.15
bower not-cached    git://github.com/angular/bower-angular-mocks.git#1.2.15
bower resolve       git://github.com/angular/bower-angular-mocks.git#1.2.15
bower not-cached    git://github.com/bestiejs/json3.git#~3.2.6
bower resolve       git://github.com/bestiejs/json3.git#~3.2.6
bower not-cached    git://github.com/twbs/bootstrap.git#~3.0.3
bower resolve       git://github.com/twbs/bootstrap.git#~3.0.3
bower download      https://github.com/angular-ui/ui-date/archive/0.0.8.tar.gz
bower download      https://github.com/es-shims/es5-shim/archive/v2.1.0.tar.gz
bower download      https://github.com/moment/moment/archive/2.8.4.tar.gz
bower download      https://github.com/angular/bower-angular-scenario/archive/v1.2.15.tar.gz
bower download      https://github.com/jquery/jquery/archive/1.11.3.tar.gz
bower download      https://github.com/angular/bower-angular-route/archive/v1.2.15.tar.gz
bower download      https://github.com/angular/bower-angular/archive/v1.2.15.tar.gz
bower download      https://github.com/bestiejs/json3/archive/v3.2.6.tar.gz
bower download      https://github.com/angular/bower-angular-cookies/archive/v1.2.15.tar.gz
bower download      https://github.com/angular/bower-angular-resource/archive/v1.2.15.tar.gz
bower download      https://github.com/angular/bower-angular-mocks/archive/v1.2.15.tar.gz
bower download      https://github.com/angular/bower-angular-sanitize/archive/v1.2.15.tar.gz
bower extract       angular-ui-date#~0.0.4 archive.tar.gz
bower resolved      git://github.com/angular-ui/ui-date.git#0.0.8
bower download      https://github.com/twbs/bootstrap/archive/v3.0.3.tar.gz
bower extract       es5-shim#~2.1.0 archive.tar.gz
bower invalid-meta  es5-shim is missing "main" entry in bower.json
bower invalid-meta  es5-shim is missing "ignore" entry in bower.json
bower resolved      git://github.com/es-shims/es5-shim.git#2.1.0
bower not-cached    git://github.com/components/jqueryui.git#^1.9
bower resolve       git://github.com/components/jqueryui.git#^1.9
bower extract       angular-route#1.2.15 archive.tar.gz
bower invalid-meta  angular-route is missing "ignore" entry in bower.json
bower resolved      git://github.com/angular/bower-angular-route.git#1.2.15
bower extract       angular-cookies#1.2.15 archive.tar.gz
bower extract       angular-resource#1.2.15 archive.tar.gz
bower invalid-meta  angular-cookies is missing "ignore" entry in bower.json
bower resolved      git://github.com/angular/bower-angular-cookies.git#1.2.15
bower invalid-meta  angular-resource is missing "ignore" entry in bower.json
bower resolved      git://github.com/angular/bower-angular-resource.git#1.2.15
bower download      https://github.com/components/jqueryui/archive/1.11.4.tar.gz
bower extract       momentjs#~2.8.3 archive.tar.gz
bower extract       angular-scenario#1.2.15 archive.tar.gz
bower extract       angular-sanitize#1.2.15 archive.tar.gz
bower invalid-meta  angular-sanitize is missing "ignore" entry in bower.json
bower resolved      git://github.com/angular/bower-angular-sanitize.git#1.2.15
bower invalid-meta  angular-scenario is missing "ignore" entry in bower.json
bower resolved      git://github.com/angular/bower-angular-scenario.git#1.2.15
bower extract       jquery#~1.11.0 archive.tar.gz
bower resolved      git://github.com/moment/moment.git#2.8.4
bower extract       angular#1.2.15 archive.tar.gz
bower invalid-meta  angular is missing "ignore" entry in bower.json
bower resolved      git://github.com/angular/bower-angular.git#1.2.15
bower extract       angular-mocks#1.2.15 archive.tar.gz
bower invalid-meta  angular-mocks is missing "ignore" entry in bower.json
bower resolved      git://github.com/angular/bower-angular-mocks.git#1.2.15
bower resolved      git://github.com/jquery/jquery.git#1.11.3
bower extract       bootstrap#~3.0.3 archive.tar.gz
bower resolved      git://github.com/twbs/bootstrap.git#3.0.3
bower extract       jquery-ui#^1.9 archive.tar.gz
bower resolved      git://github.com/components/jqueryui.git#1.11.4
bower extract       json3#~3.2.6 archive.tar.gz
bower resolved      git://github.com/bestiejs/json3.git#3.2.6
bower install       angular-ui-date#0.0.8
bower install       es5-shim#2.1.0
bower install       angular-route#1.2.15
bower install       angular-cookies#1.2.15
bower install       angular-resource#1.2.15
bower install       angular-sanitize#1.2.15
bower install       angular-scenario#1.2.15
bower install       momentjs#2.8.4
bower install       angular#1.2.15
bower install       angular-mocks#1.2.15
bower install       jquery#1.11.3
bower install       bootstrap#3.0.3
bower install       jquery-ui#1.11.4
bower install       json3#3.2.6

angular-ui-date#0.0.8 app/bower_components/angular-ui-date
├── angular#1.2.15
└── jquery-ui#1.11.4

es5-shim#2.1.0 app/bower_components/es5-shim

angular-route#1.2.15 app/bower_components/angular-route
└── angular#1.2.15

angular-cookies#1.2.15 app/bower_components/angular-cookies
└── angular#1.2.15

angular-resource#1.2.15 app/bower_components/angular-resource
└── angular#1.2.15

angular-sanitize#1.2.15 app/bower_components/angular-sanitize
└── angular#1.2.15

angular-scenario#1.2.15 app/bower_components/angular-scenario
└── angular#1.2.15

momentjs#2.8.4 app/bower_components/momentjs

angular#1.2.15 app/bower_components/angular

angular-mocks#1.2.15 app/bower_components/angular-mocks
└── angular#1.2.15

jquery#1.11.3 app/bower_components/jquery

bootstrap#3.0.3 app/bower_components/bootstrap
└── jquery#1.11.3

jquery-ui#1.11.4 app/bower_components/jquery-ui
└── jquery#1.11.3

json3#3.2.6 app/bower_components/json3

$ grunt build
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.

**Comment by ascooper57** [comment]
Hello,

I did:
 cd /Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/shimmer
 git pull
 gradle clean install installApp installDist
 cd shim-server-ui
 sudo npm install -g grunt-cli bower
 bower install
 grunt build

$ grunt build
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.

**Comment by jasperSpeicher** [comment]
Hi @ascooper57  Did you pull in the changes and re-run npm install?

**Comment by ascooper57** [comment]
Hello,

You are correct, I needed to re-run npm install before sudo npm install -g grunt-cli bower.
Thank you for resolving the issue.

Alan Cooper

**Comment by jasperSpeicher** [comment]
No problem, glad it worked out. Thank you for posting the issue here!

**Comment by haephrati** [comment]
I was also getting the same error. First make sure grunt installed locally? otherwise you may see the following message:

_Fatal error: Unable to find local grunt. If you're seeing this message, grunt hasn't been installed locally to your project. For more information about installing and configuring grunt, please see the Getting Started guide:_

The whole workaround consists of the following steps, even though not all of these steps are necessary but just to be on the safe side:

Optionally, you can uninstall and re-install grunt. That applies to your entire PC and not just to the local installation. Once you uninstall grunt, it won't be accessible from other local folders.

`npm uninstall -g grunt
`then install the grunt command line by calling:
`npm install -g grunt-cli 
`
Installing a local instance of grunt:
`npm install grunt --save-dev
`
Now you can recreate package.json by calling:

`npm init
`Then fill (or confirm) all details and it will create a new package.json file. Then, for the grunt dependencies, call:
`npm install
`

If there are errors or warnings, fix them by calling:

`npm audit fix
`

or in severe cases:

`npm audit fix --force
`
