### ISSUE TITLE
Supported APIs and endpoints

### ISSUE THREAD

**Issue by nknyc** [openmhealth/shimmer#27]
Hi,
On this page http://www.openmhealth.org/documentation/#/data-providers/data-provider-api-library/providers/fitbit - you mention the FitBit API Shim schema ID that are supported as follows (SEE ATTACHED IMAGE FITBIT_0) - 
![fitbit_0](https://cloud.githubusercontent.com/assets/14896659/10178301/ee2b2f1a-66cc-11e5-91e5-2581aadb892e.jpg)

Available Metrics

Blood glucose omh:blood-glucose:1.0 
Blood pressure omh:blood-pressure:1.0 
Body weight omh:body-weight:1.0 
Heart rate omh:heart-rate:1.0 
Physical activity omh:physical-activity:1.0 
Step count omh:step-count:1.0 

But on this page - https://github.com/openmhealth/shimmer#reading-data - you only mention the following FitBit Supported APIs and endpoints - (SEE ATTACHED IMAGE FITBIT_1) - 
![fitbit_1](https://cloud.githubusercontent.com/assets/14896659/10178311/f6c0993a-66cc-11e5-9803-2b9e362822d3.jpg)

fitbit1 activity omh:physical-activity 
fitbit1 steps omh:step-count 
fitbit1 weight omh:body-weight 
fitbit1 body_mass_index omh:body-mass-index 
fitbit1 sleep omh:sleep-duration 

I am interested to get FitBit Blood pressure omh:blood-pressure:1.0 data.  Is it possible?  The above 2 pages show discrepancy in what is possible.  Please clarify?

Thanks
NK

**Comment by schaefba** [comment]
Hi NK,

Thanks for pointing that out. Unfortunately Fitbit has deprecated the blood pressure endpoint on their side, so they no longer support accessing blood pressure information. 

It looks like some of the supported schemas for different data providers are out of date on our website, so we'll get them updated as soon as possible to reduce the confusion. The table of supported APIs and endpoints on Github is currently correct, so I'd recommend using that as a reference for the time being.

Thanks!

**Comment by schaefba** [comment]
We've updated our website to align with the information on Github. Thanks for bringing the discrepancy to our attention.
