### ISSUE TITLE
Nothing is returned when Fitbit Activity is requested as Normalized

### ISSUE THREAD

**Issue by gnauhnoj** [openmhealth/shimmer#30]
Not sure whether anyone else has run into this issue, but when normalized activity data is requested using the Fitbit API, I receive this response:

{
  "shim": "fitbit",
  "timeStamp": 1448141592,
  "body": []
}

This is the only endpoint where I'm having this issue.

**Comment by schaefba** [comment]
Hi there,

Thanks for raising this issue. We could use a little bit more information about the requests you are submitting and the data you are expecting. What is the request you are submitting to shimmer? What is the date range? And what do you expect to be returned by the request? 

If you turn normalization off (requesting raw data) and submit the same request from Fitbit, are there any data points in that response? If there are data points being returned, are there any entries in the "activities" arrays for those data points? 

The Fitbit API only returns some entries from the activity history. For example, activities entered through the Fitbit web platform using the "+ activity entry" interaction will not be returned.  If you are seeing data for a user on the Fitbit web platform or through the app and its not being retrieved by shimmer, that might be the case.

That's just one idea of what might be happening. If you can provide a little more information, we can hopefully get to the bottom of the issue!

**Comment by gnauhnoj** [comment]
Hey Chris,
Based on your response, I think I misunderstood the normalized version of activity data. When I hit the Fitbit unnormalized endpoint, I see my summary activity information, but (as I don't explicitly record activities) there is nothing in the array. I didn't realize that the normalized mHealth schema only included those explicitly recorded activities -- which is my mistake. 

Thanks for responding!
