### ISSUE TITLE
externalize application.yml

### ISSUE THREAD

**Issue by ralphvanetten** [openmhealth/shimmer#40]
It would be nice to be able to have `application.yml` loaded from a (configurable) location in the filesystem.

I know I could set `spring.config.location` but when running the shimmer from tomcat I want to have a different value for each application.

Something like `@PropertySource` looks nice but this does not work with yaml according to the documentation.

As that's about everything I know about spring I'm not sure how to implement this. Could you provide some hints on how to externalize the configuration file.

Thanks.

**Comment by emersonf** [comment]
This should be handled at the Tomcat level by setting the `spring.config.location` property per webapp. Using a different [Tomcat context parameter](http://tomcat.apache.org/tomcat-7.0-doc/config/context.html#Context_Parameters) per webapp should do it.

**Comment by emersonf** [comment]
@ralphvanetten did that take care of it?

**Comment by ralphvanetten** [comment]
Sorry, I did not had the time to test it. But from looking at the documentation it seems that it would be the correct solution.

**Comment by emersonf** [comment]
OK, I was just following up. Feel free to reply to this if it doesn't work for some reason and I'll reopen the issue.
