### ISSUE TITLE
Fitbit heart rate API

### ISSUE THREAD

**Issue by StefanoWehmix** [openmhealth/shimmer#42]
Hello,
I don't understand why Shimmer doesn't support Fitbit API of heart rate. It support heart rate call of Google Fit, Withings, Jawbone...
What should I do to add that call?

Thanks

**Comment by emersonf** [comment]
Fitbit added heart rate support recently, and the shim hasn't been updated yet. We've got an `add-fitbit-oauth2-support` feature branch ready that we'll release in the next week or two, so if you'd like to get started writing mappers for heart rate, I'd submit a pull request against that branch.

Do you have a device that can generate that data for testing purposes?

**Comment by StefanoWehmix** [comment]
Yes, I have a Fitbit device but I don't understand how to build the Shimmer code and run it natively.
Can you help me?

Thanks

**Comment by emersonf** [comment]
@StefanoWehmix the [instructions for building and running natively](https://github.com/openmhealth/shimmer#option-2-build-the-code-and-run-it-natively-or-in-docker) are in the main README.

You'd need to read the [heart rate API documentation](https://dev.fitbit.com/docs/heart-rate/) and then add the corresponding Java [mappers](https://github.com/openmhealth/shimmer/tree/master/shim-server/src/main/java/org/openmhealth/shim/fitbit) and [tests](https://github.com/openmhealth/shimmer/tree/master/shim-server/src/test/java/org/openmhealth/shim/fitbit/mapper).

We'll be working on this next week, so let us know if you intend to submit a pull request please.

**Comment by StefanoWehmix** [comment]
I think is better if you work on it because I have to understand how to work with the code before.

Thanks

**Comment by emersonf** [comment]
OK, we aim to release the heart rate mapping next week.

**Comment by afolarin** [comment]
@emersonf is there an update on HR API integration into Shimmer?

**Comment by emersonf** [comment]
Our contributor @schaefba went on sabbatical shortly after that last update, ergo the silence. We'll definitely be working on it and other Shimmer work later this year, if nobody contributes it until then, and hopefully in the next two months. We also want to line up some test devices, e.g. a Fitbit Charge HR by the time we work on it.

If you have any data, code, or testing time to contribute, let us know and we'll try to expedite.

**Comment by afolarin** [comment]
@emersonf we have a partnership API and some test data (Charge HR) would be happy to test.

**Comment by leoncard** [comment]
Are there any news regarding the HR?

**Comment by emersonf** [comment]
@leoncard @afolarin it's implemented. We'll set up a PR for it, and target getting it in early next week.

**Comment by leoncard** [comment]
@emersonf Hi Emerson, thanks for replying. I am planning to use openmhealth in my research and it would be great if this feature is available. Do you have any more updates on this? Thank you.

**Comment by afolarin** [comment]
many thanks @emersonf will look to see when this arrives.

**Comment by emersonf** [comment]
This feature was merged into Shimmer 0.5.0.
