### ISSUE TITLE
Google Fit rejects raw IP addresses in redirect URL

### ISSUE THREAD

**Issue by nileshgamit** [openmhealth/shimmer#44]
We've created Google Fit app at Google developer platform. Shimmer is hosted on AWS. When user try to connect to Google Fit, the popup appears with error, 

`Invalid parameter value for redirect_uri: Raw IP addresses not allowed: http://52.25.136.24:8083/authorize/googlefit/callback`

At time of setting up Shimmer, we used AWS dns as http://ec2-52-25-136-24.us-west-2.compute.amazonaws.com:8083/ and no-where provided IP.

No error in docker logs.

**Comment by emersonf** [comment]
Please read the thread for issue #38, specifically the updates to the `update-compose-files.sh` file.

**Comment by nileshgamit** [comment]
Hi, Thanks. It worked.
