### ISSUE TITLE
Update Fitbit shim to use OAuth 2.0

### ISSUE THREAD

**Issue by emersonf** [openmhealth/shimmer#45]
Although 1.0a support has been extended to August, "[no new OAuth 1.0a client credentials will be issued](no new OAuth 1.0a client credentials will be issued)" as of this week.

**Comment by nileshgamit** [comment]
@emersonf thanks. Is shimmer supporting OAuth 2 for FitBit? Last week, when I tried adding client id and client secret in shimmer settings, it didn't work. After going through some thread, it turned out that I need to use OAuth 1.0 client id as shimmer FitBit use it and it worked for OAuth 1 only.

**Comment by emersonf** [comment]
We're ready to release it. We were actually waiting to roll it out with any update to #43, so please let us know about that issue.

**Comment by nileshgamit** [comment]
Ok Thanks.

**Comment by emersonf** [comment]
This has been released in [v0.4.4](https://github.com/openmhealth/shimmer/releases/tag/v0.4.4).

**Comment by nileshgamit** [comment]
I've updated oAuth 2 client ID and it's giving error, like it was giving it for iHealth. Is it possible that, our application is not on secure url yet and it's causing the issue?

**Comment by emersonf** [comment]
Fitbit doesn't require TLS redirects , as shown in the [redirect table](https://github.com/openmhealth/shimmer#registering-with-third-party-apis).

**Comment by nileshgamit** [comment]
It's only working for oAuth 1.0 Client (Consumer) Key. When we updated to read OAuth 2.0 Client ID, it's no longer asking authentication and giving error. Running latest shimmer code in docker. 

Can someone please update if OAuth 2.0 is working for FitBit?
