### ISSUE TITLE
Fitbit Authentication Error Message

### ISSUE THREAD

**Issue by tomsawarynski** [openmhealth/shimmer#48]
I'm currently running a test Shimmer session via docker on a Digital Ocean Droplet and am running into the following authentication error:

"The app you're trying to connect did not provide valid information to Fitbit.  Please report the issue to them.  _Developer information:  invalid_request - Invalid redirect_uri parameter value_"

Please let me know what additional info you need to help debug.  Thx!

**Comment by emersonf** [comment]
Take a look at the [redirect URL table](https://github.com/openmhealth/shimmer#registering-with-third-party-apis) and confirm that you're configuring your application on dev.fitbit.com with a URL that Fitbit likes.

If that looks right, please also provide the URL of the popup.

**Comment by MissSharp** [comment]
@emersonf Hi, I think I've done the same thing in your website, but it brings me the same problem. This is the  URL of the popup:
https://www.fitbit.com/oauth2/authorize?client_id=2282GH&redirect_uri=http%3A%2F%2F192.168.99.100%3A8083%2Fauthorize%2Ffitbit%2Fcallback&response_type=code&scope=activity+heartrate+sleep+weight&state=WcuvBX
Thanks a lot!

**Comment by matt7tt** [comment]
Hi, can anyone confirm that the fitbit oauth 2.0 shim is now working, I have the same problem as above and have tried OAuth 2.0 App Types of Server and Client on the Fitbit App Register side with no luck, I always get the
"The app you're trying to connect did not provide valid information to Fitbit. Please report the issue to them. Developer information: invalid_request - Invalid redirect_uri parameter value"
error.
Thanks,

**Comment by emersonf** [comment]
@matt7tt I can double check, but I'm quite certain we didn't have issues with the shim up to a few weeks ago. Are you sure the _Callback URL *_ textarea on Fitbit's _Edit Application_ page contains a line that matches the `redirect_url` parameter you're sending in the authorize call?

**Comment by matt7tt** [comment]
Yes I think so: http://<myhost>:8083/authorize/fitbit/callback is the URL I am using, with the Fitbit OAuth 2.0 Client ID value and Fitbit Client Secret in my Console Fitbit settings. Please let me know if these are incorrect.
Thanks,

**Comment by devinhanaway** [comment]
I was having a very similar issue as @matt7tt , @MissSharp and @tomsawarynski when I logged in through the authorizationUrl. This was occurring because .env files do not need quotes around strings. By removing the quotes from the client_id and secret_key the redirection worked!

I hope this helps :)

**The error message I received:** 
"The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them."

_Developer information: unauthorized_client - Invalid client_id_

**Comment by emersonf** [comment]
@devinhanaway the original issue was due to incorrect redirect URIs, not incorrect client IDs. That being said, quotes will break that. :)

**Comment by emersonf** [comment]
This issue is being closed due to inactivity.
