### ISSUE TITLE
Authorization URL returns 'null' in the JSON response

### ISSUE THREAD

**Issue by manihatv** [openmhealth/shimmer#51]
Hi,

I am trying to authorize the access of Runkeeper app programmatically. I have created an application in the Runkeeper developers page and have my client ID, client secret keys. I am able to access the user's runkeeper data through the omh console dashboard. However, I want to authorize
the users programatically. Hence, as mentioned in the gitHub shimmer documentation page, I tried to make a GET request to the below URL by substituting the host address of my docker machine : 

http://<host>:8083/authorize/{shim}?username={userId} 

The following is the returned JSON response: 

{
  "id": "57481440e4b04af925c1e49b",
  "stateKey": null,
  "username": "test",
  "redirectUri": null,
  "requestParams": null,
  "authorizationUrl": null,
  "clientRedirectUrl": null,
  "isAuthorized": true,
  "serializedRequest": null
}

I tried it in the browser and in the postman plugin and both returned the 'null' value for the 'authorizationUrl' key. Can anyone help by letting me know whether the approach I follow is right ? Or am I missing something .? 

Thanks.

**Comment by manihatv** [comment]
Hi,

Can anyone please help me with this. My question may sound very microscopic as I am in the learning phase. A word of encouragement along with a possible solution to my query will be really helpful.

**Comment by manihatv** [comment]
Hi,

Can I have some suggestions in resolving this issue please.

**Comment by emersonf** [comment]
@manihatv I'll take a look tomorrow morning.

**Comment by emersonf** [comment]
The `/authorize` API call returns nulls when the user is already authorized. If you de-authorize the user `test` from the console and run

```bash
curl http://host:8083/authorize/runkeeper?username=test
```

you should get back a populated JSON object like

```json
{
    "id": "574d80f9e4b09ea8bcf42bec",
    "stateKey": "...",
    "username": "test",
    "redirectUri": "https://runkeeper.com/apps/authorize",
    "requestParams": null,
    "authorizationUrl": "https://runkeeper.com/apps/authorize?state=...&client_id=...&response_type=code&redirect_uri=...",
    "clientRedirectUrl": null,
    "isAuthorized": false,
    "serializedRequest": "..."
}```

The `isAuthorized` property is set accordingly.

**Comment by manihatv** [comment]
Thanks for the response @emersonf . I will try proceeding with the information you shared.

**Comment by emersonf** [comment]
Sounds good. I'm closing this issue, but feel free to add more comments.

**Comment by manihatv** [comment]
@emersonf The solution you suggested worked like a charm. Thank you so much for the help.
