### ISSUE TITLE
Add Microsoft Health support

### ISSUE THREAD

**Issue by Gijs-Koot** [openmhealth/shimmer#53]
Are there any plans on integrating support for the Microsoft Health platform? The company I work for is interested in this integration. We are also looking into contributing a shim for this integration, if nothing exists yet. If so, are there any pitfalls, known issues with the Microsoft Health platform or contribution guidelines that could be useful for us to be aware of?

**Comment by emersonf** [comment]
Hi Gijs,

Thanks for reaching out and offering to contribute. We've been discussing a Microsoft Health integration quite a bit, but the work hasn't started yet. The measures that the MS API supports and that we have schemas for are:

- sleep duration
- physical activity
- step count 
- heart rate

So we'd be targeting the inclusion of those mappers to start off with.

I haven't dug into the API to look at pitfalls yet. The most common issues that people face are usually in the context of rate limits, refresh tokens, and restrictions on OAuth 2 redirect URLs. So it's important to understand and capture those aspects, which we currently do in Markdown files for now, e.g. for [Google Fit](https://github.com/openmhealth/shimmer/blob/master/shim-server/src/main/java/org/openmhealth/shim/googlefit/Google-Fit.md).

Our [shim creation guidelines](http://www.openmhealth.org/documentation/#/data-providers/shim-template) are on the website. The [contribution guidelines](https://github.com/openmhealth/shimmer#contributing) are a simple explanation of Git Flow. Any feedback on either set of guidelines would be welcome.

Please let us know how you want to proceed, and hope we can work together to release MS Health support!

**Comment by Gijs-Koot** [comment]
Hi Emerson,

Thanks for your reply. As planned, I left TNO, and I'm replying to you
along with the two colleagues that are still in the project. I believe the
plans are still on the table, allthough it may take a while to get started
due to planning. I myself will no longer be involved, and I invite Victor
or Thymen to take over the conversation. Best of luck!

-- Gijs
On Jun 2, 2016 1:52 PM, "Emerson Farrugia" <notifications@github.com> wrote:

Hi Gijs,

Thanks for reaching out and offering to contribute. We've been discussing a
Microsoft Health integration quite a bit, but the work hasn't started yet.
The measures that the MS API supports and that we have schemas for are:

   - sleep duration
   - physical activity
   - step count
   - heart rate

So we'd be targeting the inclusion of those mappers to start off with.

I haven't dug into the API to look at pitfalls yet. The most common issues
that people face are usually in the context of rate limits, refresh tokens,
and restrictions on OAuth 2 redirect URLs. So it's important to understand
and capture those aspects, which we currently do in Markdown files for now,
e.g. for Google Fit
<https://github.com/openmhealth/shimmer/blob/master/shim-server/src/main/java/org/openmhealth/shim/googlefit/Google-Fit.md>
.

Our shim creation guidelines
<http://www.openmhealth.org/documentation/#/data-providers/shim-template>
are on the website. The contribution guidelines
<https://github.com/openmhealth/shimmer#contributing> are a simple
explanation of Git Flow. Any feedback on either set of guidelines would be
welcome.

Please let us know how you want to proceed, and hope we can work together
to release MS Health support!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openmhealth/shimmer/issues/53#issuecomment-223269445>,
or mute the thread
<https://github.com/notifications/unsubscribe/AEn6xURDEOQgGvOagZsiPYxA1SqZLwogks5qHsQMgaJpZM4IqitB>
.

**Comment by wwadge** [comment]
Tracked in feature/add-msband-support-pr
