### ISSUE TITLE
Shimmer Setup

### ISSUE THREAD

**Issue by RobertSloan** [openmhealth/shimmer#57]
In running Shimmer locally on a Mac:  
Fitbit needs a callback URL.   How can the locally running Shimmer (running within Docker in a VM) export a call back URL?

**Comment by RobertSloan** [comment]
The url which works is: http://192.168.99.100:8083/authorize/fitbit/callback
this url failed: http://localhost:8083/authorize/fitbit/callback
even though I forwarded ports using: docker-machine ssh default -L 8083:localhost:8083
and can browse to localhost:8083 and see the shimmer console.

**Question**:  
1) How can I access the data in the Shimmer Mongo database? Either using a terminal or programmatically?  I have Withings and Fitbit data I would like to access in an app.

**Comment by Groulien** [comment]
Concerning Mongo:
I'm a Linux user and there tend to be a lot of similarities with Mac.
I access the database through the docker container like this:
`docker exec -it <container code> mongo`
Which gives me a Mongo cli. If you' re unfamiliar with it, just type 'help' once you're in.

*However*, your authorization problem may be a different one.

**Cause**
After login, Fitbit redirects to a callback url with an access code.
Then, Shimmer will redeem the code for an oauth token. During this it 'echoes' the callback url to Fitbit.
I think Shimmer isn't sending the right url.

**Possible Fix**
I did it one of two ways.
1. Update the ``OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE`` in  ``docker-compose.yml`` and ``run docker-compose  up -d`` again.
2. Update the ``OPENMHEALTH_SHIM_SERVER_CALLBACKURLBASE`` in  ``docker-compose-build.yml`` and ``./run-dockerized.sh``.

**Comment by RobertSloan** [comment]
Groulien:   Thanks for your explanation.  I now understand what Mongo is used for in Shimmer.
Originally In Installation: Option 1 - I skipped step 4 as my compose version 1.71 was > 1.5 but this step should not be skipped.
After a bit I have successfully gotten Shimmer running both locally on the Mac and on Digital Ocean.
