### ISSUE TITLE
Pull in GPS data

### ISSUE THREAD

**Issue by SimonFricker** [openmhealth/shimmer#70]
Can we pull in GPS data from Fitbit (and soon the Moves app)

**Comment by NiekHoekstra** [comment]
As stated in the readme, Shimmer supplies information using the Open mHealth format.
At the time of writing this feature is not part of the format and would not be added to Shimmer.

Your best to get this feature is to motivate the [ohm-developers](https://groups.google.com/forum/#!forum/omh-developers) Google group to discuss this or ask for this feature at the [Open mHealth schemas](https://github.com/openmhealth/schemas) repository.

**Comment by emersonf** [comment]
Shimmer now pulls in geoposition data from Google Fit. I'm not aware of Fitbit providing any via its APIs. Moves support may be added down the road, but it's not something currently scheduled.
