### ISSUE TITLE
iHealth configuration problem

### ISSUE THREAD

**Issue by miawan** [openmhealth/shimmer#72]
Hi, 

I am new to these kind of stuff, i am testing shimmer with different api, i can perfectly complete integration with fitbit e.t.c. but I m having trouble with iHealth integration, please help me on that. Documentation said "You'll need to copy the iHealth SC and SV values found via the application management page into the openmhealth.shim.ihealth.serialValues map of the application.yaml file." but it doesn't describe it in more detail. In application.yaml file i can see 
"ihealth:
      serialValues:
        SC: [5e5ba9a1bae34824aaf9db2e44f8f2e4]
        sportSV: [YOUR_SV_VALUE_FOR_THE_SPORT_ENDPOINT]
        bloodPressureSC: [5e5ba9a1bae34824aaf9db2e44f8f2e4]
        bloodPressureSV: [3306b4a70f134d0eb1a815f6db2ab015]
        spo2SV: [7c17d191d6d142169734bd6bb19a921e]
        weightSV: [ abba687b4201488bb29b656a013719ad]
        bloodGlucoseSV: [ 27405c8215be4db59aa67af401083754]
        activitySV: [ a2d48bf0f5a046d4a130e0e08ddd34be]
        sleepSV: [ 29144ec8ea624d5a864221f6b8635b53]
      clientId: [a6ab351588c34c2b8394eceab41301f9]"  
but i can't understand that and here is only one place for SC and what's SC will i put here, i tried it in different ways but it didn't work for me. Please help me in this.

**Comment by alphazhe** [comment]
Try using without square brackets
`ihealth:
serialValues:
SC: 5e5ba9a1bae34824aaf9db2e44f8f2e4
sportSV: YOUR_SV_VALUE_FOR_THE_SPORT_ENDPOINT
bloodPressureSC: 5e5ba9a1bae34824aaf9db2e44f8f2e4
bloodPressureSV: 3306b4a70f134d0eb1a815f6db2ab015
spo2SV: 7c17d191d6d142169734bd6bb19a921e
weightSV:  abba687b4201488bb29b656a013719ad
bloodGlucoseSV:  27405c8215be4db59aa67af401083754
activitySV:  a2d48bf0f5a046d4a130e0e08ddd34be
sleepSV:  29144ec8ea624d5a864221f6b8635b53
clientId: a6ab351588c34c2b8394eceab41301f9`

**Comment by emersonf** [comment]
For anyone seeing this issue, please check the documentation since the configuration property names have changed.
