### ISSUE TITLE
Integration with my own App

### ISSUE THREAD

**Issue by luistduarte** [openmhealth/shimmer#73]
Hello, i want integrate omh with my own app, is it possible? For example, with my android app push data to omh. I dont want to use standard APIs like google fit or fitbit, just omh

**Comment by NiekHoekstra** [comment]
**Disclaimer: I am not part of the Open mHealth organisation**
The database used by OmH is only used to store credentials.
It is a gateway to other API's and returns the information in a standardized format.
Storage of the information is not part of the project as different developers have different needs, and therefore need different solution.

**Comment by luistduarte** [comment]
For it i used omh-dsu-ri repository, Sorry for my newbie question..
