### ISSUE TITLE
Limitation in data query

### ISSUE THREAD

**Issue by allen1996** [openmhealth/shimmer#85]
At the moment shimmer can only query data in days only, we can't query data in any finer details such as hour or minute. Is there any workaround to achieve that?

**Comment by wwadge** [comment]
Hi,

From the docs: "Uses the daily activity summary when partner access is disabled (default) and uses intraday activity when partner access is enabled. See the YAML configuration file for details. Intraday activity requests are limited to 24 hours worth of data per request."

**Comment by emersonf** [comment]
@allen1996 take a look at PR 64. It had missed my radar (sorry @ntrous). If that's what you're after, let us know. We're trying to make time for Shimmer as best we can.

**Comment by allen1996** [comment]
Thank you @emersonf , I had a look at the commit from nitrous. Just to confirm, does it allows us to pull data from different shims with time (such as 2016-07-12T13:00:00) as query parameter.
