### ISSUE TITLE
Push endpoint

### ISSUE THREAD

**Issue by ZuSe** [openmhealth/shimmer#86]
Hi folks,

first of all I would like to thank you for the amazing project and work you do.
I really like the idea about having a standardized format for all mobile health data - especially from a developer perspective it speeds up things a lot.

We are currently providing in our app support for Withings and iHealth. In the beginning we fetched data from their api but as of today we mainly use their PubSub endpoint, that is pushing newly created health values directly into our system.
So my question: Are you guys going to support this way of transferring data as well?

Best,
Patrick

**Comment by emersonf** [comment]
Hi @ZuSe, 

We don't have anything on our roadmap for handling push notifications for now. Of the APIs that support push, many have different delivery guarantees  and it becomes too easy to miss data, e.g. during downtime. 

If we do tackle it, we'll update the documentation and mention it in our release notes.
