### ISSUE TITLE
UserRedirectRequiredException occurred when retrieved data from shimmer after a week for same user.

### ISSUE THREAD

**Issue by waqaslatif88** [openmhealth/shimmer#87]
Hi, I have an application which uses shimmer server for device data retrieval and user authentication , First time authentication and retrieval working fine but after a week same user tries to retrieve data from fitbit but below exception occurred .

Scenario : First time User got authenticated and get their data and then after a week when user try to get his recent data then  UserRedirectRequiredException exception occurred. 

 
{\"timestamp\":\"2017-06-12T08:27:00.344+0000\",\"status\":500,\"error\":\"Internal Server Error\",\"exception\":\"org.springframework.security.oauth2.client.resource.UserRedirectRequiredException\",\"message\":\"org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.security.oauth2.client.resource.UserRedirectRequiredException: A redirect is required to get the users approval\",\"path\":\"/data/fitbit/weight\"}

Please advice.

**Comment by emersonf** [comment]
@waqaslatif88 thanks for the report and sorry for the late reply. Did you make progress on this?

**Comment by emersonf** [comment]
This issue has been closed due to inactivity.
