### ISSUE TITLE
Shimmer 0.5.0 compiling issue

### ISSUE THREAD

**Issue by giandrea77** [openmhealth/shimmer#92]
Hello,

I followed the instructions and I'm getting this error running from bash:

* What went wrong:
Could not resolve all files for configuration ':java-shim-sdk:compileClasspath'.
> Could not find org.openmhealth.schema:omh-schema-sdk:1.2.1.
  Searched in the following locations:
      file:/home/andrea/.m2/repository/org/openmhealth/schema/omh-schema-sdk/1.2.1/omh-schema-sdk-1.2.1.pom
      file:/home/andrea/.m2/repository/org/openmhealth/schema/omh-schema-sdk/1.2.1/omh-schema-sdk-1.2.1.jar
      https://jcenter.bintray.com/org/openmhealth/schema/omh-schema-sdk/1.2.1/omh-schema-sdk-1.2.1.pom
      https://jcenter.bintray.com/org/openmhealth/schema/omh-schema-sdk/1.2.1/omh-schema-sdk-1.2.1.jar
  Required by:
      project :java-shim-sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

FYI: same thing is happening with 0.6.0 version

**Comment by emersonf** [comment]
@giandrea77 I forgot the manual publishing step on Bintray, sorry about that. They're published now.
