### ISSUE TITLE
Error message on Fitbit callback

### ISSUE THREAD

**Issue by olivierbufalini** [openmhealth/shimmer#98]

**Comment by olivierbufalini** [comment]
I am trying to get shimmer working with Fitbit but every time I get this error message on Fitbit call back : {"type":"ERROR","details":"Access token denied.","accessParameters":null,"requestParameters":null}

I am testing locally on a docker image on my Mac but I have ngrok tunneling the port 8083 to my machine, it s working fine with Google Fit and Withings but I had no chance so far with Fitbit. 

Also the authorizationUrl I am getting with postman is : https://www.fitbit.com/oauth2/authorize?response_type=code&client_id=22CKHK&redirect_uri=http://localhost:8083/authorize/fitbit/callback&scope=activity%20heartrate%20sleep%20weight&state=TmxxEu&prompt=login%20consent

The redirect_uri is always localhost, how can I change that, is there any settings ? the api base url in postman is mapped to my ngrok tunnel.

Thanks

**Comment by shannoneobrien** [comment]
Any luck resolving your issue? We are experiencing something similar. @olivierbufalini

**Comment by olivierbufalini** [comment]
@shannoneobrien just edit that file https://github.com/openmhealth/shimmer/blob/master/shim-server/src/main/resources/application.yaml#L23 and change it with your domain name. Once it s done if you are using Docker you ll need to : 
Shutdown dockers
docker-compose down 

Rebuild war following changes
./gradlew build


Rebuild the Docker and start standalone process
docker-compose -f docker-compose-build.yml build
docker-compose -f docker-compose-build.yml up -d
